### ISSUE TITLE
Update spidocheTube for Compatibility With JQuery 3

### ISSUE THREAD

**Issue by SebastienGicquel** [spidoche/spidocheTube#1]
Hello,

I want to implement your plugin in Drupal 8 which natively use 3.2.1 and the player doesn’t show up. I’ve tried on your demo (really basic demo) with jQuery 3.2.1 and I have the same issue. Is it possible to make the plugin compatible with latest jQuery version ?

Her is the issue the error console 

> TypeError: undefined is not a function (near '...}).complete(function(){...')

**Comment by SebastienGicquel** [comment]
If I delete `.complete(function(){`

and leave code inside the `complete()`, it works.

**Comment by spidoche** [comment]
I just merge your commit and update the demo of the doc
Thank you for the fix.
